INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO users (username,password_hash,role) VALUES ('volunteer','$2a$10$g5I16pPHztrGqbyGrrfzDem2NlnlSSwYdGgrASaEM.M82TIW/wjIK','ROLE_VOLUNTEER');



insert into animals (name, breed, age, bio, animal_type_id) values ('Teddy', 'English Mastiff', 4, 'Open-architected analyzing model', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Gertrude', 'Bichon Frisé', 8, 'Business-focused systematic service-desk', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Moxie Vanderbeagle', 'Mutt', 6, 'Seamless bottom-line leverage', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Maggie', 'Great Pyrenees', 4, 'Configurable high-level alliance', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Boba Fetch', 'Chihuahua/Terrier', 10, 'User-centric real-time definition', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Lance', 'Chiahuahua Mix', 4, 'Innovative maximized function', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Roxy', 'Australian Shepherd', 4, 'Enhanced explicit methodology', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Emerald', 'Boxer/Husky', 1, 'Operative regional system engine', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Burt', 'Mutt', 3, 'Ergonomic composite task-force', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Juno', 'Mutt', 1, 'Distributed local collaboration', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Willow', 'Beagle', 9, 'Monitored background methodology', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Daisy Doo', 'Chihuahua', 5, 'Organic dynamic parallelism', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Gus', 'Bichon Yorkie', 8, 'Visionary interactive framework', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Robin', 'Cattle Dog', 1, 'Re-engineered tertiary strategy', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Buster', 'Mutt', 4, 'Open-source radical complexity', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Oscar', 'Corgi', 3, 'Darn sweetest pup ever!', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Patricia', 'Newfoundland', 1, 'Robust holistic array', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Shinji', 'Shiba Inu', 4, 'Enterprise-wide secondary ability', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Darill', 'Basset Hound', 7, 'Multi-lateral attitude-oriented service-desk', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Patches', 'Husky', 8, 'Ameliorated needs-based emulation', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Ivie', 'Husky', 5, 'Cross-group bi-directional conglomeration', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Cooper', 'Lab', 11, 'Fully-configurable zero tolerance monitoring', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Norah', 'Mutt', 8, 'Up-sized fresh-thinking functionalities', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Gidget', 'Toy Poodle', 16, 'Sharable explicit benchmark', 1);
insert into animals (name, breed, age, bio, animal_type_id) values ('Kauri', 'Pit Mix', 1, 'Realigned mission-critical interface', 1);

insert into animals (name, breed, age, bio, animal_type_id) values ('Peppermint Patty', 'Domestic Shorthair', 6, 'Operative 5th generation parallelism', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Nancy', 'Domestic Shorthair', 5, 'Synchronised 6th generation middleware', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Greta', 'Domestic Shorthair', 3, 'De-engineered leading edge instruction set', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Tate', 'Domestic Shorthair', 7, 'Switchable homogeneous paradigm', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Jack', 'Domestic Shorthair', 1, 'Customizable bandwidth-monitored help-desk', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Misha', 'Domestic Shorthair', 6, 'Managed context-sensitive encoding', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Crystal', 'Domestic Shorthair', 7, 'Vision-oriented exuding focus group', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Felix', 'Domestic Shorthair', 5, 'Fundamental modular secured line', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Muppet', 'Domestic Shorthair', 5, 'Secured disintermediate budgetary management', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Mitzy', 'Domestic Shorthair', 9, 'Intuitive static collaboration', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Mama Cat', 'Domestic Shorthair', 6, 'Mandatory discrete attitude', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Fireball', 'Domestic Shorthair', 5, 'Distributed actuating Graphic Interface', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Garfield', 'Domestic Shorthair', 5, 'Focused hybrid strategy', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Paisley', 'Domestic Shorthair', 2, 'Multi-lateral bifurcated approach', 2);
insert into animals (name, breed, age, bio, animal_type_id) values ('Sasha', 'Domestic Shorthair', 7, 'Diverse neutral intranet', 2);

insert into animals (name, breed, age, bio, animal_type_id) values ('Biddy', 'Horse', 7, 'Universal hybrid open system', 3);
insert into animals (name, breed, age, bio, animal_type_id) values ('Delmor', 'Cow', 4, 'Realigned background local area network', 3);
insert into animals (name, breed, age, bio, animal_type_id) values ('Griffin', 'Horse', 1, 'Robust attitude-oriented interface', 3);
insert into animals (name, breed, age, bio, animal_type_id) values ('Caroljean', 'Goat', 6, 'Public-key neutral moratorium', 3);
insert into animals (name, breed, age, bio, animal_type_id) values ('Quincy', 'Horse', 7, 'Organized global artificial intelligence', 3);

insert into animals (name, breed, age, bio, animal_type_id) values ('Dolores', 'Rabbit', 2, 'Switchable upward-trending workforce', 4);
insert into animals (name, breed, age, bio, animal_type_id) values ('Pryce', 'Boa', 2, 'Streamlined bottom-line encoding', 4);
insert into animals (name, breed, age, bio, animal_type_id) values ('Angie', 'Guinea Pig', 2, 'Profit-focused explicit protocol', 4);
insert into animals (name, breed, age, bio, animal_type_id) values ('Shelley', 'Hedgehog', 1, 'Advanced didactic internet solution', 4);
insert into animals (name, breed, age, bio, animal_type_id) values ('Kronk', 'Bearded Dragon', 5, 'Switchable solution-oriented Graphical User Interface', 4);

insert into animal_photos (animal_id, photo_link) values (1, 'https://i.imgur.com/Yds4Jka.jpg');
insert into animal_photos (animal_id, photo_link) values (2, 'https://i.imgur.com/QfzzdII.jpg');
insert into animal_photos (animal_id, photo_link) values (3, 'https://i.imgur.com/CaGYWdO.jpg');
insert into animal_photos (animal_id, photo_link) values (4, 'https://i.imgur.com/BAtqSRk.jpg');
insert into animal_photos (animal_id, photo_link) values (5, 'https://i.imgur.com/xDNtGzS.jpg');
insert into animal_photos (animal_id, photo_link) values (6, 'https://i.imgur.com/DlKKD1U.jpg');
insert into animal_photos (animal_id, photo_link) values (7, 'https://i.imgur.com/8fdvd5L.jpg');
insert into animal_photos (animal_id, photo_link) values (8, 'https://i.imgur.com/aqrEWU0.jpg');
insert into animal_photos (animal_id, photo_link) values (9, 'https://i.imgur.com/ZTgvr0j.png');
insert into animal_photos (animal_id, photo_link) values ( 10, 'https://i.imgur.com/qCdHA8W.jpg');
insert into animal_photos (animal_id, photo_link) values ( 11, 'https://i.imgur.com/5NsOQY8.jpg');
insert into animal_photos (animal_id, photo_link) values ( 12, 'https://i.imgur.com/J2feUJB.jpg');
insert into animal_photos (animal_id, photo_link) values ( 13, 'https://i.imgur.com/xUsyV0k.jpg');
insert into animal_photos (animal_id, photo_link) values ( 14, 'https://i.imgur.com/oOQeCJV.jpg');
insert into animal_photos (animal_id, photo_link) values ( 15, 'https://i.imgur.com/L1YDJa7.jpg');
insert into animal_photos (animal_id, photo_link) values ( 16, 'https://i.imgur.com/OBhBxbh.jpg');
insert into animal_photos (animal_id, photo_link) values ( 17, 'https://i.imgur.com/7EAJi2Y.jpg');
insert into animal_photos (animal_id, photo_link) values ( 18, 'https://i.imgur.com/CkmEbfN.jpg');
insert into animal_photos (animal_id, photo_link) values ( 19, 'https://i.imgur.com/tlwinbv.jpg');
insert into animal_photos (animal_id, photo_link) values ( 20, 'https://i.imgur.com/dZjsMz1.jpg');
insert into animal_photos (animal_id, photo_link) values ( 21, 'https://i.imgur.com/emxvOXe.jpg?1');
insert into animal_photos (animal_id, photo_link) values ( 22, 'https://i.imgur.com/aVjk7qx.jpg');
insert into animal_photos (animal_id, photo_link) values ( 23, 'https://i.imgur.com/H7AbgxS.png');
insert into animal_photos (animal_id, photo_link) values ( 24, 'https://i.imgur.com/4JIRZoo.jpg');
insert into animal_photos (animal_id, photo_link) values ( 25, 'https://i.imgur.com/95TwgZa.jpg');
insert into animal_photos (animal_id, photo_link) values ( 26, 'https://i.imgur.com/IqxPTSq.jpg');
insert into animal_photos (animal_id, photo_link) values ( 27, 'https://i.imgur.com/YtRBXEw.jpg');
insert into animal_photos (animal_id, photo_link) values ( 28, 'https://i.imgur.com/2Hmr2zP.jpg');
insert into animal_photos (animal_id, photo_link) values ( 29, 'https://i.imgur.com/YMfg4yD.jpg');
insert into animal_photos (animal_id, photo_link) values ( 30, 'https://i.imgur.com/p27ofEB.jpg');
insert into animal_photos (animal_id, photo_link) values ( 31, 'https://i.imgur.com/IiUeMag.jpg');
insert into animal_photos (animal_id, photo_link) values ( 32, 'https://i.imgur.com/T4jS1M8.jpg');
insert into animal_photos (animal_id, photo_link) values ( 33, 'https://i.imgur.com/qhapnnj.jpg');
insert into animal_photos (animal_id, photo_link) values ( 34, 'https://i.imgur.com/ygHfGxe.jpg');
insert into animal_photos (animal_id, photo_link) values ( 35, 'https://i.imgur.com/EZKSjiM.jpg');
insert into animal_photos (animal_id, photo_link) values ( 36, 'https://i.imgur.com/j6wyZ7u.jpg');
insert into animal_photos (animal_id, photo_link) values ( 37, 'https://i.imgur.com/wJgb78l.jpg');
insert into animal_photos (animal_id, photo_link) values ( 38, 'https://i.imgur.com/oeMUtOT.jpg');
insert into animal_photos (animal_id, photo_link) values ( 39, 'https://i.imgur.com/LNPo3wN.jpg');
insert into animal_photos (animal_id, photo_link) values ( 40, 'https://i.imgur.com/t3ASpsv.jpg');
insert into animal_photos (animal_id, photo_link) values ( 41, 'https://i.imgur.com/rDY69GI.jpg');
insert into animal_photos (animal_id, photo_link) values ( 42, 'https://i.imgur.com/5zTCYIY.jpg');
insert into animal_photos (animal_id, photo_link) values ( 43, 'https://i.imgur.com/Y0G46Jl.jpg');
insert into animal_photos (animal_id, photo_link) values ( 44, 'https://i.imgur.com/w6xO1f2.jpg');
insert into animal_photos (animal_id, photo_link) values ( 45, 'https://i.imgur.com/buPqwFf.jpg');
insert into animal_photos (animal_id, photo_link) values ( 46, 'https://i.imgur.com/TcFFHws.jpg');
insert into animal_photos (animal_id, photo_link) values ( 47, 'https://i.imgur.com/5PPoIcW.jpg');
insert into animal_photos (animal_id, photo_link) values ( 48, 'https://i.imgur.com/mtE9IlJ.jpg');
insert into animal_photos (animal_id, photo_link) values ( 49, 'https://i.imgur.com/ICowzcc.jpg');
insert into animal_photos (animal_id, photo_link) values ( 50, 'https://i.imgur.com/w7sWBbu.jpg');


insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Hillie Mattia', '944-491-0613', 'gmckeighen0@google.com.hk', 'Automated 24/7 encoding', 'Guillaume McKeighen', '328-838-1038', 'gmckeighen0@omniture.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Symon Goacher', '562-327-4719', 'cberrow1@imgur.com', 'Public-key real-time service-desk', 'Calypso Berrow', '446-922-2732', 'cberrow1@buzzfeed.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Carlin Sjostrom', '871-901-0513', 'dwyburn2@storify.com', 'Integrated value-added alliance', 'Donaugh Wyburn', '516-835-5504', 'dwyburn2@columbia.edu');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Arlen Torrese', '264-858-4249', 'gkropp3@51.la', 'Up-sized human-resource open architecture', 'Gayler Kropp', '619-276-7496', 'gkropp3@blogger.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Jesselyn Sibbit', '949-321-4606', 'hmannin4@blog.com', 'Re-contextualized even-keeled open architecture', 'Harley Mannin', '985-602-1481', 'hmannin4@examiner.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Bud Eggleson', '186-377-5459', 'atapply5@google.it', 'Grass-roots multi-state framework', 'Anatola Tapply', '291-685-4412', 'atapply5@globo.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Joseph Deverell', '742-334-8053', 'ttraher6@flickr.com', 'Organic radical array', 'Tish Traher', '800-884-8810', 'ttraher6@google.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Vidovic MacGarrity', '555-994-3657', 'csucre7@pen.io', 'Future-proofed actuating leverage', 'Christen Sucre', '394-926-1703', 'csucre7@soup.io');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Abbey Trodd', '849-973-4014', 'mmccloughlin8@fc2.com', 'Fundamental actuating protocol', 'Maximo McCloughlin', '484-892-0323', 'mmccloughlin8@hubpages.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Gerik MacDavitt', '154-996-6170', 'bsenyard9@state.gov', 'Optional hybrid definition', 'Bill Senyard', '244-248-1761', 'bsenyard9@who.int');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Mischa Antoniou', '664-321-1045', 'dtamletta@joomla.org', 'Future-proofed mission-critical model', 'Daveta Tamlett', '328-235-4015', 'dtamletta@meetup.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Huntington Thorbon', '151-378-5848', 'gbrownsillb@dyndns.org', 'Re-contextualized clear-thinking secured line', 'Gianna Brownsill', '329-871-4790', 'gbrownsillb@joomla.org');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Kathi Tatem', '693-250-9103', 'dbezzantc@so-net.ne.jp', 'Balanced responsive budgetary management', 'Dalenna Bezzant', '228-908-6623', 'dbezzantc@acquirethisname.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Tuck MacDaid', '624-922-7826', 'tboormand@shinystat.com', 'Intuitive heuristic groupware', 'Trumann Boorman', '857-528-3577', 'tboormand@google.com.br');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Ida Hilland', '409-140-1663', 'rstollhofere@wikia.com', 'Pre-emptive disintermediate leverage', 'Raina Stollhofer', '616-631-0640', 'rstollhofere@rakuten.co.jp');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Dede Grimsdith', '699-984-9971', 'afilintsevf@hibu.com', 'Self-enabling encompassing model', 'Aindrea Filintsev', '517-191-5639', 'afilintsevf@harvard.edu');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Shem Vaud', '477-430-0245', 'sberryclothg@example.com', 'Fundamental modular function', 'Starla Berrycloth', '369-854-4954', 'sberryclothg@123-reg.co.uk');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Marylynne Champkins', '213-154-9303', 'dparradyeh@gov.uk', 'Centralized even-keeled concept', 'Danita Parradye', '904-766-8402', 'dparradyeh@moonfruit.com');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Britt Frake', '851-176-8241', 'awesoni@businesswire.com', 'Synchronised grid-enabled conglomeration', 'Adel Weson', '771-644-8067', 'awesoni@altervista.org');
insert into volunteers (full_name, phone_number, email, bio, ref_full_name, ref_phone_number, ref_email) values ('Belicia Redford', '693-467-3013', 'ewadhamj@auda.org.au', 'Cloned context-sensitive flexibility', 'Erick Wadham', '788-907-3353', 'ewadhamj@jiathis.com');
